/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/CRT.glb -o src/components/CRTModel.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    Apple2_Computer_Computer_0: THREE.Mesh
    Apple2_Driver_Driver_0: THREE.Mesh
    Apple2_Driver2_Driver2_0: THREE.Mesh
    Apple2_Monitor_Monitor_0: THREE.Mesh
  }
  materials: {
    Computer: THREE.MeshStandardMaterial
    Driver: THREE.MeshStandardMaterial
    Driver2: THREE.MeshStandardMaterial
    Monitor: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/CRT.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Apple2_Computer_Computer_0.geometry} material={materials.Computer} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Apple2_Driver_Driver_0.geometry} material={materials.Driver} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Apple2_Driver2_Driver2_0.geometry} material={materials.Driver2} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Apple2_Monitor_Monitor_0.geometry} material={materials.Monitor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/CRT.glb')
